### ISSUE TITLE
Several default shortcuts aren't overridden

### ISSUE THREAD

**Issue by lmintmate** [pragmader/navimacs#2]
I installed your extension in Firefox 55.0.2 under Linux Mint, and when I tried to use it found out that the default actions Firefox assigns to these shortcuts weren't overridden. C-n opened a new window, C-p tried to print, C-f launched the search, and C-b launched the side column. The only features that worked as expected were M-< and M->, which did scroll to the top and bottom of the page.
I tried then to test out the extension in Chrome 61, and again the same thing happened i.e. most of the default shortcuts weren't overridden with the Navimacs ones - the only differences in comparison to Firefox were that C-b did nothing, while both M-< and M-> go to the top of the page.
I have to admit, out of these behaviors I do care to keep the C-f one binded to search (unless you manage to offer C-s for that instead in the future, overriding the default save behavior), but otherwise I don't care about keeping most of the other behaviors.
This probably means that the shortcuts should override the browser default ones by default, while the extension should in tandem offer a way for the user to override said shortcuts and rebind them to the default ones, e.g. if he wants to keep C-f to the default binding, but not everything else.
Thanks in advance for understanding.

**Comment by pragmader** [comment]
Right, I tested only on Mac, sorry for that.
I'm not sure if it's possible to override Firefox key bindings from a web extension but I'll have a look into it. 

Also, your help is welcome, this extension is pretty damn simple ;)
