### ISSUE TITLE
C-n still isn't overridden (Firefox & Chrome, Linux Mint)

### ISSUE THREAD

**Issue by lmintmate** [pragmader/navimacs#7]
I tried the new version of your extension on the same configurations as before (Firefox 55.0.2 and Chrome 61 on Linux Mint 18.2, based on Ubuntu LTS 16.04), and almost everything else works as expected now, but C-n still opens a new window instead of scrolling down on both browsers. 
I have no idea what could cause this not to work, but not affect everything else, and I unfortunately cannot help you fix the issue either (since you did invite me to do so last time), as I don't know enough Javascript to be able to fix things.
Thanks in advance for understanding.

**Comment by pragmader** [comment]
Hm, seems like the "open tab" behavior works in a different way in the browser. So, it's [impossible to intercept these](https://stackoverflow.com/questions/7295508/javascript-capture-browser-shortcuts-ctrlt-n-w).

I'd suggest to find a way how to change default Firefox shortcuts.

**Comment by lmintmate** [comment]
Just found out that C-n [isn't intended to be overidden](https://github.com/lusakasa/saka-key/issues/53#issuecomment-332319791) because of security reasons, so it's practically impossible to implement that keyboard shortcut. Such a pity...
